# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mePyGuis\guis\calcIsotopeEnrichmentDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1195, 1109)
        Dialog.setStyleSheet(_fromUtf8("background-color: white;"))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(950, 1060, 221, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(19, 25, 1161, 568))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(
            _fromUtf8(
                "background-image: url(:/EnrichmentDialog/resources/EnrichmentDialog.png)"
            )
        )
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 600, 1151, 451))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(50)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "#1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "#2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "#3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "#4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "#5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "#6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "#7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "#8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "#9", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "#10", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "#11", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "#12", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "#13", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "#14", None))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "#15", None))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "#16", None))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "#17", None))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "#18", None))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "#19", None))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "#20", None))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Dialog", "#21", None))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("Dialog", "#22", None))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("Dialog", "#23", None))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("Dialog", "#24", None))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("Dialog", "#25", None))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("Dialog", "#26", None))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("Dialog", "#27", None))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("Dialog", "#28", None))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("Dialog", "#29", None))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("Dialog", "#30", None))
        item = self.tableWidget.verticalHeaderItem(30)
        item.setText(_translate("Dialog", "#31", None))
        item = self.tableWidget.verticalHeaderItem(31)
        item.setText(_translate("Dialog", "#32", None))
        item = self.tableWidget.verticalHeaderItem(32)
        item.setText(_translate("Dialog", "#33", None))
        item = self.tableWidget.verticalHeaderItem(33)
        item.setText(_translate("Dialog", "#34", None))
        item = self.tableWidget.verticalHeaderItem(34)
        item.setText(_translate("Dialog", "#35", None))
        item = self.tableWidget.verticalHeaderItem(35)
        item.setText(_translate("Dialog", "#36", None))
        item = self.tableWidget.verticalHeaderItem(36)
        item.setText(_translate("Dialog", "#37", None))
        item = self.tableWidget.verticalHeaderItem(37)
        item.setText(_translate("Dialog", "#38", None))
        item = self.tableWidget.verticalHeaderItem(38)
        item.setText(_translate("Dialog", "#39", None))
        item = self.tableWidget.verticalHeaderItem(39)
        item.setText(_translate("Dialog", "#40", None))
        item = self.tableWidget.verticalHeaderItem(40)
        item.setText(_translate("Dialog", "#41", None))
        item = self.tableWidget.verticalHeaderItem(41)
        item.setText(_translate("Dialog", "#42", None))
        item = self.tableWidget.verticalHeaderItem(42)
        item.setText(_translate("Dialog", "#43", None))
        item = self.tableWidget.verticalHeaderItem(43)
        item.setText(_translate("Dialog", "#44", None))
        item = self.tableWidget.verticalHeaderItem(44)
        item.setText(_translate("Dialog", "#45", None))
        item = self.tableWidget.verticalHeaderItem(45)
        item.setText(_translate("Dialog", "#46", None))
        item = self.tableWidget.verticalHeaderItem(46)
        item.setText(_translate("Dialog", "#47", None))
        item = self.tableWidget.verticalHeaderItem(47)
        item.setText(_translate("Dialog", "#48", None))
        item = self.tableWidget.verticalHeaderItem(48)
        item.setText(_translate("Dialog", "#49", None))
        item = self.tableWidget.verticalHeaderItem(49)
        item.setText(_translate("Dialog", "#50", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Abundance M", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Abundance M+1", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Abundance M'-1", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Abundance M'", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Xn", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "M enrichment", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "M' enrichment", None))


import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
