# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mePyGuis\guis\FTICRwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1369, 907)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.loadedSamples = QtGui.QListView(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadedSamples.sizePolicy().hasHeightForWidth())
        self.loadedSamples.setSizePolicy(sizePolicy)
        self.loadedSamples.setMinimumSize(QtCore.QSize(0, 0))
        self.loadedSamples.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.loadedSamples.setObjectName(_fromUtf8("loadedSamples"))
        self.gridLayout.addWidget(self.loadedSamples, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.results = QtGui.QTreeWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results.sizePolicy().hasHeightForWidth())
        self.results.setSizePolicy(sizePolicy)
        self.results.setMinimumSize(QtCore.QSize(350, 0))
        self.results.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.results.setObjectName(_fromUtf8("results"))
        self.gridLayout.addWidget(self.results, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.result_MassSpectrum = QtGui.QWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_MassSpectrum.sizePolicy().hasHeightForWidth())
        self.result_MassSpectrum.setSizePolicy(sizePolicy)
        self.result_MassSpectrum.setObjectName(_fromUtf8("result_MassSpectrum"))
        self.gridLayout_3.addWidget(self.result_MassSpectrum, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.matchPPM = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.matchPPM.setProperty("value", 0.5)
        self.matchPPM.setObjectName(_fromUtf8("matchPPM"))
        self.gridLayout_4.addWidget(self.matchPPM, 0, 1, 1, 1)
        self.bracketingPPM = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.bracketingPPM.setProperty("value", 2.0)
        self.bracketingPPM.setObjectName(_fromUtf8("bracketingPPM"))
        self.gridLayout_4.addWidget(self.bracketingPPM, 1, 1, 1, 1)
        self.process = QtGui.QPushButton(self.groupBox_2)
        self.process.setObjectName(_fromUtf8("process"))
        self.gridLayout_4.addWidget(self.process, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 2)
        self.annotationPPM = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.annotationPPM.setProperty("value", 0.5)
        self.annotationPPM.setObjectName(_fromUtf8("annotationPPM"))
        self.gridLayout_5.addWidget(self.annotationPPM, 0, 2, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.SGRElements_min = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SGRElements_min.sizePolicy().hasHeightForWidth())
        self.SGRElements_min.setSizePolicy(sizePolicy)
        self.SGRElements_min.setObjectName(_fromUtf8("SGRElements_min"))
        self.gridLayout_6.addWidget(self.SGRElements_min, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.SGRElements_max = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SGRElements_max.sizePolicy().hasHeightForWidth())
        self.SGRElements_max.setSizePolicy(sizePolicy)
        self.SGRElements_max.setObjectName(_fromUtf8("SGRElements_max"))
        self.gridLayout_6.addWidget(self.SGRElements_max, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 1, 0, 1, 3)
        self.useSevenGoldenRules = QtGui.QCheckBox(self.groupBox_4)
        self.useSevenGoldenRules.setChecked(True)
        self.useSevenGoldenRules.setObjectName(_fromUtf8("useSevenGoldenRules"))
        self.gridLayout_5.addWidget(self.useSevenGoldenRules, 4, 0, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_samples = QtGui.QAction(MainWindow)
        self.actionLoad_samples.setObjectName(_fromUtf8("actionLoad_samples"))
        self.actionSave_results = QtGui.QAction(MainWindow)
        self.actionSave_results.setObjectName(_fromUtf8("actionSave_results"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLoad_results = QtGui.QAction(MainWindow)
        self.actionLoad_results.setObjectName(_fromUtf8("actionLoad_results"))
        self.menuFile.addAction(self.actionLoad_samples)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MetExtract II - FT-ICR module", None))
        self.groupBox.setTitle(_translate("MainWindow", "Loaded samples and results", None))
        self.label_4.setText(_translate("MainWindow", "Samples", None))
        self.label_5.setText(_translate("MainWindow", "Results", None))
        self.results.headerItem().setText(0, _translate("MainWindow", "MZ", None))
        self.results.headerItem().setText(1, _translate("MainWindow", "Cn", None))
        self.results.headerItem().setText(2, _translate("MainWindow", "-", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Process samples", None))
        self.label_9.setText(_translate("MainWindow", "Match ppm", None))
        self.process.setText(_translate("MainWindow", "Process", None))
        self.label_10.setText(_translate("MainWindow", "Bracketing ppm", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sum formula generation", None))
        self.label.setText(_translate("MainWindow", "Annotation ppm", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Elements for sum formula generation", None))
        self.label_3.setText(_translate("MainWindow", "Min", None))
        self.SGRElements_min.setText(_translate("MainWindow", "CH", None))
        self.label_6.setText(_translate("MainWindow", "Max", None))
        self.SGRElements_max.setText(_translate("MainWindow", "CH1000N10O100S10P10", None))
        self.useSevenGoldenRules.setText(_translate("MainWindow", "Use Seven Golden Rules (Kind et al. 2007)", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionLoad_samples.setText(_translate("MainWindow", "Load samples", None))
        self.actionSave_results.setText(_translate("MainWindow", "Save results", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLoad_results.setText(_translate("MainWindow", "Load results", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

