# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mePyGuis\guis\groupEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_GroupEditor(object):
    def setupUi(self, GroupEditor):
        GroupEditor.setObjectName(_fromUtf8("GroupEditor"))
        GroupEditor.resize(781, 552)
        GroupEditor.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtWidgets.QGridLayout(GroupEditor)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtWidgets.QLabel(GroupEditor)
        self.label_3.setStyleSheet(_fromUtf8("font: 10pt;"))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 7, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(GroupEditor)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 2, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(3, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(GroupEditor)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(3, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.groupName = QtWidgets.QLineEdit(GroupEditor)
        self.groupName.setAcceptDrops(False)
        self.groupName.setPlaceholderText(_fromUtf8(""))
        self.groupName.setObjectName(_fromUtf8("groupName"))
        self.gridLayout_2.addWidget(self.groupName, 1, 4, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.dialogFinished = QtWidgets.QPushButton(GroupEditor)
        self.dialogFinished.setObjectName(_fromUtf8("dialogFinished"))
        self.horizontalLayout_2.addWidget(self.dialogFinished)
        self.dialogCanceled = QtWidgets.QPushButton(GroupEditor)
        self.dialogCanceled.setObjectName(_fromUtf8("dialogCanceled"))
        self.horizontalLayout_2.addWidget(self.dialogCanceled)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 9, 4, 1, 1)
        self.line = QtWidgets.QFrame(GroupEditor)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 0, 1, 5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtWidgets.QLabel(GroupEditor)
        self.label_2.setStyleSheet(_fromUtf8("font: 10pt;"))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.label_6 = QtWidgets.QLabel(GroupEditor)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(90, 90, 90);\n"
"font: 7pt;"))
        self.label_6.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(200, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.verticalLayout, 4, 0, 2, 1)
        self.groupFiles = QtWidgets.QListWidget(GroupEditor)
        self.groupFiles.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.groupFiles.setObjectName(_fromUtf8("groupFiles"))
        self.gridLayout_2.addWidget(self.groupFiles, 4, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.addFolder = QtWidgets.QPushButton(GroupEditor)
        self.addFolder.setObjectName(_fromUtf8("addFolder"))
        self.horizontalLayout.addWidget(self.addFolder)
        self.addFiles = QtWidgets.QPushButton(GroupEditor)
        self.addFiles.setObjectName(_fromUtf8("addFiles"))
        self.horizontalLayout.addWidget(self.addFiles)
        self.removeSelected = QtWidgets.QPushButton(GroupEditor)
        self.removeSelected.setObjectName(_fromUtf8("removeSelected"))
        self.horizontalLayout.addWidget(self.removeSelected)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 4, 1, 1)
        self.line_5 = QtWidgets.QFrame(GroupEditor)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_2.addWidget(self.line_5, 6, 0, 1, 5)
        self.line_6 = QtWidgets.QFrame(GroupEditor)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_2.addWidget(self.line_6, 8, 0, 1, 5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtWidgets.QLabel(GroupEditor)
        self.label_5.setStyleSheet(_fromUtf8("font: 10pt;"))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 9, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtWidgets.QLabel(GroupEditor)
        self.label.setStyleSheet(_fromUtf8("font: 10pt;"))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(GroupEditor)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 4, 2, 2, 1)
        self.line_7 = QtWidgets.QFrame(GroupEditor)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_2.addWidget(self.line_7, 7, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(GroupEditor)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_2.addWidget(self.line_8, 9, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.useAsMSMSTarget = QtWidgets.QCheckBox(GroupEditor)
        self.useAsMSMSTarget.setObjectName(_fromUtf8("useAsMSMSTarget"))
        self.gridLayout_3.addWidget(self.useAsMSMSTarget, 5, 1, 1, 3)
        self.removeAsFalsePositive = QtWidgets.QCheckBox(GroupEditor)
        self.removeAsFalsePositive.setObjectName(_fromUtf8("removeAsFalsePositive"))
        self.gridLayout_3.addWidget(self.removeAsFalsePositive, 4, 1, 1, 3)
        self.useForMetaboliteGrouping = QtWidgets.QCheckBox(GroupEditor)
        self.useForMetaboliteGrouping.setChecked(True)
        self.useForMetaboliteGrouping.setObjectName(_fromUtf8("useForMetaboliteGrouping"))
        self.gridLayout_3.addWidget(self.useForMetaboliteGrouping, 3, 1, 1, 3)
        self.omitFeatures = QtWidgets.QGroupBox(GroupEditor)
        self.omitFeatures.setCheckable(True)
        self.omitFeatures.setObjectName(_fromUtf8("omitFeatures"))
        self.gridLayout_4 = QtWidgets.QGridLayout(self.omitFeatures)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtWidgets.QLabel(self.omitFeatures)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.groupMinimumFound = QtWidgets.QSpinBox(self.omitFeatures)
        self.groupMinimumFound.setMinimum(1)
        self.groupMinimumFound.setMaximum(999)
        self.groupMinimumFound.setProperty("value", 1)
        self.groupMinimumFound.setObjectName(_fromUtf8("groupMinimumFound"))
        self.gridLayout_4.addWidget(self.groupMinimumFound, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.omitFeatures, 1, 1, 2, 3)
        self.colorsComboBox = QtWidgets.QComboBox(GroupEditor)
        self.colorsComboBox.setObjectName(_fromUtf8("colorsComboBox"))
        self.gridLayout_3.addWidget(self.colorsComboBox, 0, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(GroupEditor)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 0, 6, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 7, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 3)

        self.retranslateUi(GroupEditor)
        QtCore.QMetaObject.connectSlotsByName(GroupEditor)
        GroupEditor.setTabOrder(self.dialogFinished, self.groupName)
        GroupEditor.setTabOrder(self.groupName, self.groupFiles)
        GroupEditor.setTabOrder(self.groupFiles, self.addFolder)
        GroupEditor.setTabOrder(self.addFolder, self.addFiles)
        GroupEditor.setTabOrder(self.addFiles, self.removeSelected)
        GroupEditor.setTabOrder(self.removeSelected, self.useForMetaboliteGrouping)
        GroupEditor.setTabOrder(self.useForMetaboliteGrouping, self.removeAsFalsePositive)
        GroupEditor.setTabOrder(self.removeAsFalsePositive, self.useAsMSMSTarget)
        GroupEditor.setTabOrder(self.useAsMSMSTarget, self.dialogCanceled)

    def retranslateUi(self, GroupEditor):
        GroupEditor.setWindowTitle(_translate("GroupEditor", "Dialog", None))
        self.label_3.setText(_translate("GroupEditor", "Options", None))
        self.dialogFinished.setText(_translate("GroupEditor", "Ok", None))
        self.dialogCanceled.setText(_translate("GroupEditor", "Cancel", None))
        self.label_2.setText(_translate("GroupEditor", "Files", None))
        self.label_6.setText(_translate("GroupEditor", "<html><head/><body><p>Specify the measurement files for this group</p></body></html>", None))
        self.addFolder.setText(_translate("GroupEditor", "Add folder", None))
        self.addFiles.setText(_translate("GroupEditor", "Add file(s)", None))
        self.removeSelected.setText(_translate("GroupEditor", "Remove selected", None))
        self.label_5.setText(_translate("GroupEditor", "Actions", None))
        self.label.setText(_translate("GroupEditor", "Group name", None))
        self.useAsMSMSTarget.setText(_translate("GroupEditor", "Use sample for MSMS targets", None))
        self.removeAsFalsePositive.setText(_translate("GroupEditor", "Remove (false positive)", None))
        self.useForMetaboliteGrouping.setText(_translate("GroupEditor", "Use samples for metabolite grouping", None))
        self.omitFeatures.setTitle(_translate("GroupEditor", "Omit features", None))
        self.label_4.setText(_translate("GroupEditor", "Minimum found ", None))
        self.label_7.setText(_translate("GroupEditor", "Color", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroupEditor = QtWidgets.QDialog()
    ui = Ui_GroupEditor()
    ui.setupUi(GroupEditor)
    GroupEditor.show()
    sys.exit(app.exec())

